### ISSUE TITLE
Raw scores for figure 2, comparing Accuracy@K on test-data of NQ-Open

### ISSUE THREAD

**Issue by akhilkedia** [KNOT-FIT-BUT/R2-D2#1]
Can you provide the raw data in the figure 2 of your preprint paper, which compares Accuracy@K on test-data of NQ-Open?

**Comment by akhilkedia** [comment]
While I can read the approximate values of this accuracy from the figure, actual values will be very helpful!

**Comment by xondre09** [comment]
Hello @akhilkedia,
the raw data that we used to plot Figure 2 and Figures 6-9 in the Appendix can be found at the following link:
https://docs.google.com/spreadsheets/d/1Nkao4XVTIpjpOBAd1A7u6qWKb6XBDnTXnSvD20RDTJU/edit?usp=sharing

The Google sheet contains data for the EfficientQA, NQ-open, and TriviaQA datasets. The 'reader' columns contain the accuracy@k where we use the reader's passage score to rerank top-200 passages from retriever.

**Comment by akhilkedia** [comment]
Thank you. Closing.
