### ISSUE TITLE
how to process if one quesiton has multiple answers?

### ISSUE THREAD

**Issue by xilinniao123** [KNOT-FIT-BUT/R2-D2#2]
thanks for sharing, how to process this situation one quesiton has multiple answers?

**Comment by MFajcik** [comment]
Hello @hitxujian , our work wasn't really focusing on these cases. TriviaQA and Natural Questions only contain examples with single answer.

There are multiple reasons why question might have multiple answers, such as (a) the question was ambiguous, and different answer depends on different context (b) the answer is a list of spans (not really multiple answers in the true sense of "answer").

If you are interested in (a) case, I can recommend checking this work I read a while ago
https://arxiv.org/pdf/2104.08445.pdf

It doesn't seem the code has been released though.
