### ISSUE TITLE
Is it possible to run this on my own dataset?

### ISSUE THREAD

**Issue by beejaya** [KNOT-FIT-BUT/R2-D2#3]
@mdocekal @MFajcik Thanks for sharing this. Is it possible to use this on my problem statement: I have a document and a set of questions. Can I use this code and produce an answer if there is an answer in my document. If there is no answer, say that there is no answer. If so, I would appreciate if you can give me some pointers on how to do it.
Thanks.

**Comment by MFajcik** [comment]
The issue was somehow forgotten (I found it here after an year 👍 ). Please reopen if you still need an advice.
